### PR TITLE
start testing of writing key files

### PR DESCRIPTION
**Pull request by cryptix**
* [ ] serialize public portion
* [ ] serialize private portion
* [ ] find (how to recreate) the keyid number

### CODE REVIEW

**Comment by cryptix** [comment]
First insights:

- for some reason the dnskey includes a TTL..?
- the output for the private key doesnt seem to care about the timestamps

```
[nix-shell:~/Documents/sig0namectl/sig0namectl/golang/sig0]$ go test
2024/04/26 13:29:12 /tmp/Kgo.te.st.+015+25564.key import: go.te.st. 3600 1 25 512 3 15 z99eWZyFtCykenwjr0Dy3/UVgfNVLzvPrxl9Ts4KGqg=
2024/04/26 13:29:12 key import: go.te.st. 3600 1 25 512 3 15 NocEDRqG0cq4pOC7YiCoHlQROREIbWyA1p2gGElkso8=
--- FAIL: TestParseKeyFile (0.02s)
    keys_test.go:73: created key file: /tmp/Kgo.te.st.+015+17486
    keys_test.go:48: pk type: ed25519.PrivateKey
    keys_test.go:55:
        	Error Trace:	/Users/cryptix/Documents/sig0namectl/sig0namectl/golang/sig0/keys_test.go:55
        	Error:      	Not equal:
        	            	expected: "go.te.st. IN KEY 512 3 15 NocEDRqG0cq4pOC7YiCoHlQROREIbWyA1p2gGElkso8=\n"
        	            	actual  : "go.te.st. 3600 IN KEY 512 3 15 NocEDRqG0cq4pOC7YiCoHlQROREIbWyA1p2gGElkso8="

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1 @@
        	            	-go.te.st. IN KEY 512 3 15 NocEDRqG0cq4pOC7YiCoHlQROREIbWyA1p2gGElkso8=
        	            	-
        	            	+go.te.st. 3600 IN KEY 512 3 15 NocEDRqG0cq4pOC7YiCoHlQROREIbWyA1p2gGElkso8=
        	Test:       	TestParseKeyFile
    keys_test.go:58:
        	Error Trace:	/Users/cryptix/Documents/sig0namectl/sig0namectl/golang/sig0/keys_test.go:58
        	Error:      	Not equal:
        	            	expected: "Private-key-format: v1.3\nAlgorithm: 15 (ED25519)\nPrivateKey: x7SwB5YnJrKQ1egATs9MvIjSvXli/ovq71XfzqAZ0O4=\nCreated: 20240426092912\nPublish: 20240426092912\nActivate: 20240426092912\n"
        	            	actual  : "Private-key-format: v1.3\nAlgorithm: 15 (ED25519)\nPrivateKey: x7SwB5YnJrKQ1egATs9MvIjSvXli/ovq71XfzqAZ0O4=\n"

        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -3,5 +3,2 @@
        	            	 PrivateKey: x7SwB5YnJrKQ1egATs9MvIjSvXli/ovq71XfzqAZ0O4=
        	            	-Created: 20240426092912
        	            	-Publish: 20240426092912
        	            	-Activate: 20240426092912

```

**Comment by adam-burns** [comment]
TTL of 3600 is picked up as a default [here](https://github.com/NetworkCommons/sig0namectl/blob/3620d542b6085065bad1b3f9282aef0f953b9949/golang/sig0/keys.go#L30)

Not sure whether the go module allows it to be excluded, but at least in nsupdate & bind9 zone files you can define default values for zones that get inserted if not explicitly entered (and by default dnssec-keygen excludes TTL but can also add one with -L). If the module doesn't, you may have to split it out for the test, or give default in keygen? 

Not sure yet which is best approach. IIRC, I don't *think* any current bash script manipulates or scans *.key files where an additional TTL field would break functionality. In fact I think it's all left to nsupdate itself?

**Comment by adam-burns** [comment]
adding -L 60 to dnssec-keygen almost gets it (but not yet sure is best way, as we already have keys generated without by default)

```
$ go test
2024/04/26 13:20:15 /tmp/Kgo.te.st.+015+42856.key import: go.te.st. 60 1 25 512 3 15 jFHIp8XkmP9A4fD4/d3TWnWrIgx3+qxazcw07th1VCs=
2024/04/26 13:20:15 key import: go.te.st. 60 1 25 512 3 15 3bgC21OE/ir4zK9FBp24dAHGNwBC2AwQPjEh3/5XQEg=
--- FAIL: TestParseKeyFile (0.01s)
    keys_test.go:73: created key file: /tmp/Kgo.te.st.+015+50389
    keys_test.go:48: pk type: ed25519.PrivateKey
    keys_test.go:55: 
                Error Trace:    /home/vortex/src/sig0namectl/golang/sig0/keys_test.go:55
                Error:          Not equal: 
                                expected: "go.te.st. 60 IN KEY 512 3 15 3bgC21OE/ir4zK9FBp24dAHGNwBC2AwQPjEh3/5XQEg=\n"
                                actual  : "go.te.st. 60 IN KEY 512 3 15 3bgC21OE/ir4zK9FBp24dAHGNwBC2AwQPjEh3/5XQEg="
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,2 +1 @@
                                 go.te.st. 60 IN KEY 512 3 15 3bgC21OE/ir4zK9FBp24dAHGNwBC2AwQPjEh3/5XQEg=
                                -
                Test:           TestParseKeyFile
    keys_test.go:58: 
                Error Trace:    /home/vortex/src/sig0namectl/golang/sig0/keys_test.go:58
                Error:          Not equal: 
                                expected: "Private-key-format: v1.3\nAlgorithm: 15 (ED25519)\nPrivateKey: ePUexE3PABNCKFrdYE9H0/UDWPQodo4FL3ejfgpR8io=\nCreated: 20240426112015\nPublish: 20240426112015\nActivate: 20240426112015\n"
                                actual  : "Private-key-format: v1.3\nAlgorithm: 15 (ED25519)\nPrivateKey: ePUexE3PABNCKFrdYE9H0/UDWPQodo4FL3ejfgpR8io=\n"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -3,5 +3,2 @@
                                 PrivateKey: ePUexE3PABNCKFrdYE9H0/UDWPQodo4FL3ejfgpR8io=
                                -Created: 20240426112015
                                -Publish: 20240426112015
                                -Activate: 20240426112015
                                 
                Test:           TestParseKeyFile
2024/04/26 13:20:15 /tmp/Kgo.te.st.+015+10429.key import: go.te.st. 60 1 25 512 3 15 ylSDg+MbTS0dLKnz2Ul5JmQmpfAZLbQ5cTPGj1PTKOg=
2024/04/26 13:20:15 -- Set dns.Msg Structure --
2024/04/26 13:20:15 -- Attach RR to dns.Msg --
2024/04/26 13:20:15 -- Create, fill & attach SIG RR to dns.Msg Structure --
FAIL
exit status 1
FAIL    github.com/NetworkCommons/sig0namectl/sig0      0.025s

```

**Comment by adam-burns** [comment]
Oh, & for key tag / key id (or whatever they're calling it this week, see the function [KeyTag() in dns go module](https://github.com/miekg/dns/blob/e4ef594946b6b32be31cecd5b8c84be3cad21405/dnssec.go#L131-L170) that should do the trick.

**Pull request closed without merging**
